project_id = "dixtfwozrmeelrolxvwk"

[functions.notify-run-started]
verify_jwt = false

[functions.notify-item-added]
verify_jwt = false

[functions.guest-login]
verify_jwt = false

[functions.privacy-policy]
verify_jwt = false

[functions.support]
verify_jwt = false
